name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker Image
        run: docker build -t my-lambda ./fetch_db_data/team_stats

      - name: Tag Docker Image
        run: docker tag my-lambda:latest 779533547175.dkr.ecr.us-east-1.amazonaws.com/yahoo-dashboard-ecr:latest

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR
        run: docker push 779533547175.dkr.ecr.us-east-1.amazonaws.com/yahoo-dashboard-ecr:latest

      - name: Update Lambda Function to Use Latest Image
        run: |
          aws lambda update-function-code \
              --function-name pull-leaderboard-fantasy-data \
              --image-uri 779533547175.dkr.ecr.us-east-1.amazonaws.com/yahoo-dashboard-ecr:latest
