name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Lambda package
        run: |
          mkdir package
          pip install -r requirements.txt -t package/
          cp fetch_data.py constants.py package/
          cd package
          zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name get_fantasy_scores --zip-file fileb://lambda.zip
          echo "Deployment successful - sleeping for 10 seconds to allow the function to update before uploading env vars..."
          sleep 3
          aws lambda update-function-configuration --function-name get_fantasy_scores --environment "Variables={DEVELOPMENT=${{ secrets.DEVELOPMENT }},SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}}"
