name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Package code and dependencies
        run: |
          zip -r lambda.zip .

      - name: Deploy to Lambda
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          zip -r lambda.zip .
          aws lambda update-function-code --function-name get_fantasy_scores --zip-file fileb://lambda.zip
          echo "Deployment successful - sleeping for 10 seconds to allow the function to update before uploading env vars..."
          sleep 10
          aws lambda update-function-configuration --function-name get_fantasy_scores --environment "Variables={DEVELOPMENT=${{ secrets.DEVELOPMENT }},SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}}"
